version: '3'

tasks:
  test:
    cmds:
      # The idiomatic way to disable test caching explicitly is to use -count=1
      - go test ./internal/... -count=1 -v --failfast

  lint:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin
      - $GOPATH/bin/golangci-lint run -v -c .golangci.yml ./...

  install:
    cmds:
      - go build -o $GOPATH/bin/argocd-mcp-server main.go
 
  install-argocd-mock:
    cmds:
      - go build -o $GOPATH/bin/argocd-mock test/e2e/argocd-mock/main.go

  test-e2e:
    deps:
      - install
      - install-argocd-mock
    cmds:
      # The idiomatic way to disable test caching explicitly is to use -count=1
      - go test github.com/codeready-toolchain/argocd-mcp-server/test/e2e/... -count=1 -v -failfast

  build-image:
    cmds:
      - podman build -t argocd-mcp-server:latest . -f Containerfile.yaml
